### ISSUE TITLE
String to code

### ISSUE THREAD

**Issue by stephanemagnenat** [pyfisch/keyboard-types#10]
PR #4 added `FromStr` trait for `Key`, however, there is no equivalent for `Code`. When used on the web, it feels natural to me to want to create a `Code` from an `js_sys::KeyboardEvent::code()`. Given that the two specification files are somewhat similar, it should not be too hard to add. Or do I miss something?

**Comment by pyfisch** [comment]
`Code` is very similar to `Key`. One needs to change `convert.py` to add an implementation and then rebuild the crate.

You want to send a PR?

**Comment by stephanemagnenat** [comment]
PR done, see #10.
