### ISSUE TITLE
#![no_std] support?

### ISSUE THREAD

**Issue by thejpster** [pyfisch/keyboard-types#2]
Hi. I'm about to write a PS/2 keyboard driver for an embedded device (https://github.com/thejpster/monotron). Would you be interested in making this crate `#![no_std]` so I could use it in my project? Thanks!

**Comment by pyfisch** [comment]
Hi,

> Would you be interested in making this crate #![no_std] so I could use it in my project?

If this helps you, definitely. Can you send in a PR? It should be easy. Only CompositionEvent requires allocation if I recall correctly.
