### ISSUE TITLE
F13 through F35 keys

### ISSUE THREAD

**Issue by waywardmonkeys** [pyfisch/keyboard-types#31]
In https://github.com/pyfisch/keyboard-types/commit/59ab770285cb9a37ab055c8af6562882f3c6eca8, @pyfisch has support for F13-F35 keys.

Any chance that could land as part of the current batch of changes for a new release?

**Comment by pyfisch** [comment]
Sure. Mind to add the convert.py changes to #26?

**Comment by waywardmonkeys** [comment]
Okay I will.
