### ISSUE TITLE
Add `Key::Finish`

### ISSUE THREAD

**Issue by ArturKovacs** [pyfisch/keyboard-types#9]
As you may know I'm in the progress of implementing the new winit keyboard input API [here](https://github.com/ArturKovacs/winit/tree/new-keyboard). I found another key variant which was missing, namely `Finish`. See: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

Opening an issue for this might be overkill but this seemed to be the most appropriate medium for communicating this.

**Comment by pyfisch** [comment]
Curiously the `Finish` key is not part of <https://w3c.github.io/uievents-key/>. I didn't find a lot of information about this key, do you know a keyboard with this key?

According to the Firefox source code it is a Nokia and Ericsson specific (mobile phone?) key. If I am reading <https://hg.mozilla.org/mozilla-central/file/tip/widget/windows/KeyboardLayout.cpp> correctly it isn't really handled by Firefox but ignored.

If we are convinced that this key is present on contemporary hardware the correct way forward is to amend the UIEvents key specification.

> Opening an issue for this might be overkill but this seemed to be the most appropriate medium for communicating this.

This is perfect for an issue imho. Its a small and well-defined problem, we can discuss here without cluttering any other discussion forum.

**Comment by ArturKovacs** [comment]
> I didn't find a lot of information about this key, do you know a keyboard with this key?

Frankly, I don't. I searched for `VK_OEM_FINISH` around GitHub and there's a bunch of code referring to it but all I could see was either just the definition of the constant or using it in a table which converts a scancode to a virtual keycode. The most interesting definition I found was [this](https://github.com/ataceyhun/old-src/blob/98bd914d250dd72a85e351da1ec3aa88433aac35/nt/private/ntos/w32/ntuser/inc/vkoem.h) and I found other sources that also suggest that it's some old Nokia/Ericsson stuff but I can't find anything that actually uses it or any page that would describe what this button is.

So at this point I'm just super curious and a bit too invested but this doesn't seem to be required.

@mwallnoefer I can see you made a [change to the MDN page](https://wiki.developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values$compare?to=1564782&from=1473090) specifying which IE versions the described behaviour was tested with. I would be more than delighted if you could let us know what this button is for. 😊

**Comment by mwallnoefer** [comment]
Oh, that was already more than a year ago. I just extended the IE 9 keymap to IE 11, but I haven't tested all the keys in detail, sorry.

**Comment by ArturKovacs** [comment]
That's alright. Thanks for getting back to us this quickly anyways.

Considering what we know so far, to me it seems perfectly reasonable to leave `Finish` out for now. If someone needs it, they can always open a PR.
